postgres:
  build: ./compose/postgres
  volumes:
    - /data/spistresci/postgres:/var/lib/postgresql/data
    - /data/spistresci/postgres-backups:/backups
  env_file: .env

django:
  build: .
  user: django
  links:
    - postgres
    - redis
  command: /gunicorn.sh
  env_file: .env

nginx:
  build: ./compose/nginx/
  links:
    - django
  env_file: .env

redis:
  image: redis:3.0

celeryworker:
  build: .
  user: django
  env_file: .env
  links:
   - postgres
   - redis
  command: celery -A spistresci.taskapp worker -l INFO

celerybeat:
  build: .
  user: django
  env_file: .env
  links:
    - postgres
    - redis
  command: celery -A spistresci.taskapp beat -l INFO
