from AddBookTest import AddBookTest
from AddBookUTF8Test import AddBookUTF8Test
from ConnectorsUpdateManagementCommandTest \
    import ConnectorsUpdateManagementCommandTest
from DeleteOrphanRecordsManagementCommandTest \
    import DeleteOrphanRecordsManagementCommandTest