from GenericConnector import GenericConnector
from GenericConnector import GenericBook
from GenericConnector import GenericISBN
from GenericConnector import GenericBookDescription
from GenericConnector import GenericAuthor
from GenericConnector import GenericBookPrice
from GenericConnector import GenericBooksAuthors
from GenericConnector import GenericBooksISBNs
from GenericConnector import GenericBase

from XMLConnector import XMLConnector
