from GenericConnector import GenericConnector
from GenericConnector import GenericBook
from GenericConnector import GenericBookDescription
from GenericConnector import GenericAuthor
from XMLConnector import XMLConnector
